variable "dev-rgs" {}
variable "dev-stgs" {}
variable "dev-cons" {}
variable "dev-vnets" {}
variable "dev-win-vms" {}
variable "dev-nsgs" {}
variable "dev-asgs" {}
variable "dev-bastions" {}
variable "dev-keyvaults" {}